WITH project_schedule_publishing_scheduled AS (
    select 
       id,
       received_at,
       context_traits_tos_version_1_0,
       context_traits_widget_auth_token,
       timestamp,
       context_traits_auth_providers_github_email,
       context_traits_auth_providers_github_username,
       context_traits_auth_providers_sanity_email,
       context_traits_created_at,
       context_traits_nux,
       context_library_name,
       context_traits_auth_providers_sanity_provider_user_id,
       context_traits_display_name,
       event,
       context_traits_updated_at,
       context_traits_temporary,
       user_id,
       utc_scheduled_date,
       context_traits_auth_providers_netlify_email,
       context_traits_connections,
       context_traits_email,
       context_traits_v,
       project_id,
       context_traits_auth_providers_github_provider_user_id,
       context_traits_auth_providers_netlify_provider_user_id,
       context_traits_id,
       event_text,
       uuid_ts,
       context_library_version,
       context_traits_auth_providers_email_provider_user_id,
       context_traits_preferences_dashboard_links_hint_dismissed,
       context_traits_auth_providers_sanity_display_name,
       context_user_agent,
       original_timestamp,
       sent_at,
       context_traits_auth_providers_contentful_display_name,
       context_traits_auth_providers_netlify_display_name,
       context_traits_auth_providers_github_display_name,
       context_traits_auth_providers_netlify_username,
       context_traits_auth_providers_contentful_provider_user_id,
       context_traits_auth_providers_forestry_email,
       context_traits_auth_providers_forestry_provider_user_id,
       context_traits_auth_providers_contentful_email,
       context_traits_auth_providers_forestry_display_name,
       context_traits_auth_providers_email_email,
       context_traits_email_verification,
       context_traits_surveys,
       context_traits_auth_providers_google_display_name,
       context_traits_auth_providers_google_email,
       context_traits_auth_providers_google_provider_user_id,
       context_traits_analytics_initial_traffic_source,
       context_traits_auth_providers_azure_provider_user_id,
       context_traits_analytics_initial_referrer_landing,
       context_traits_auth_providers_azure_email,
       context_traits_analytics_initial_referrer,
       context_traits_preferences_exclusive_platforms,
       context_traits_unverified_email,
       context_traits_organization_memberships,
       context_traits_stripe_customer_id,
       context_traits_favorite_projects,
       organization_id
    from {{ source('api_stackbit_com_production', 'project_schedule_publishing_scheduled') }}
),

final as (
    select *
    from project_schedule_publishing_scheduled
)

select *
from final