WITH webhook_sanity AS (
    select 
       id,
       received_at,
       original_timestamp,
       context_traits_auth_providers_google_provider_user_id,
       context_traits_auth_providers_sanity_display_name,
       context_traits_email,
       context_user_agent,
       event_text,
       sent_at,
       uuid_ts,
       context_traits_auth_providers_email_reset_password_expires,
       context_traits_auth_providers_github_provider_user_id,
       context_traits_auth_providers_netlify_provider_user_id,
       context_traits_created_at,
       context_traits_email_verification,
       context_traits_preferences_dashboard_links_hint_dismissed,
       context_library_version,
       context_traits_auth_providers_contentful_display_name,
       context_traits_auth_providers_email_provider_user_id,
       context_traits_auth_providers_github_display_name,
       context_traits_auth_providers_sanity_email,
       context_traits_id,
       context_traits_v,
       context_traits_widget_auth_token,
       context_traits_auth_providers_email_email,
       context_traits_auth_providers_email_reset_password_token,
       context_traits_auth_providers_forestry_provider_user_id,
       context_traits_auth_providers_netlify_display_name,
       context_library_name,
       context_traits_auth_providers_github_email,
       context_traits_auth_providers_sanity_provider_user_id,
       context_traits_auth_providers_google_display_name,
       context_traits_auth_providers_netlify_email,
       context_traits_temporary,
       context_traits_tos_version_1_0,
       context_traits_auth_providers_contentful_email,
       context_traits_auth_providers_contentful_provider_user_id,
       context_traits_auth_providers_forestry_display_name,
       context_traits_auth_providers_forestry_email,
       project_id,
       timestamp,
       context_traits_auth_providers_github_username,
       context_traits_display_name,
       event,
       user_id,
       context_traits_auth_providers_google_email,
       context_traits_auth_providers_netlify_username,
       context_traits_connections,
       context_traits_updated_at,
       context_traits_nux,
       context_traits_stripe_customer_id,
       context_traits_surveys,
       context_traits_analytics_initial_referrer,
       context_traits_analytics_initial_referrer_landing,
       context_traits_analytics_initial_traffic_source,
       context_traits_auth_providers_azure_provider_user_id,
       context_traits_auth_providers_azure_email,
       context_traits_unverified_email,
       context_traits_preferences_exclusive_platforms,
       context_traits_organization_memberships,
       project_wizard_settings_enable_widget,
       project_wizard_settings_public_repo_required,
       project_wizard_settings_advanced_github_permissions_required,
       project_wizard_settings_import_type,
       project_wizard_settings_is_annotation_based,
       project_wizard_settings_cms_exclusive,
       project_wizard_settings_referrer,
       project_wizard_settings_studio_version,
       project_wizard_settings_analytics_subdomain_created_by,
       project_wizard_settings_analytics_branch_created_by,
       context_traits_analytics_initial_utm_medium,
       context_traits_analytics_initial_utm_source,
       context_traits_analytics_initial_utm_campaign,
       context_traits_auth_providers_workos_email,
       context_traits_auth_providers_workos_display_name,
       context_traits_auth_providers_workos_provider_user_id,
       context_traits_auth_providers_workos_username,
       organization_id,
       project_wizard_settings_assets_source,
       context_traits_favorite_projects,
       anonymous_id
    from {{ source('api_stackbit_com_production', 'webhook_sanity') }}
),

final as (
    select *
    from webhook_sanity
)

select *
from final